"""drop stored holdings columns from agent_positions

Revision ID: f305a3e51bae
Revises: c2a43ab83bc0
Create Date: 2026-02-07 12:17:16.083854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f305a3e51bae'
down_revision = 'c2a43ab83bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_agent_positions', 'vault_shares')
    op.drop_column('tbl_agent_positions', 'collateral_amount')
    op.drop_column('tbl_agent_positions', 'borrow_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_agent_positions', sa.Column('borrow_amount', sa.NUMERIC(precision=78, scale=0), autoincrement=False, nullable=False))
    op.add_column('tbl_agent_positions', sa.Column('collateral_amount', sa.NUMERIC(precision=78, scale=0), autoincrement=False, nullable=False))
    op.add_column('tbl_agent_positions', sa.Column('vault_shares', sa.NUMERIC(precision=78, scale=0), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
