"""add wallet address to agents table

Revision ID: c2a43ab83bc0
Revises: db16f43422e1
Create Date: 2026-02-04 19:52:25.193809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a43ab83bc0'
down_revision = 'db16f43422e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_agents', sa.Column('wallet_address', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_agents', 'wallet_address')
    # ### end Alembic commands ###
