"""initial schema with users agents positions and chat events

Revision ID: db16f43422e1
Revises: 
Create Date: 2026-02-03 14:15:43.476836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db16f43422e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_agent_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_agent_actions_agent_id'), 'tbl_agent_actions', ['agent_id'], unique=False)
    op.create_table('tbl_agent_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('collateral_asset', sa.Text(), nullable=False),
    sa.Column('collateral_amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('borrow_amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('target_ltv', sa.Float(), nullable=False),
    sa.Column('vault_shares', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('morpho_market_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_agent_positions_agent_id'), 'tbl_agent_positions', ['agent_id'], unique=False)
    op.create_table('tbl_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), nullable=False),
    sa.Column('agent_index', sa.Integer(), nullable=False),
    sa.Column('ens_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_chat_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_chat_events_agent_id'), 'tbl_chat_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tbl_chat_events_user_id'), 'tbl_chat_events', ['user_id'], unique=False)
    op.create_table('tbl_user_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address', name='tbl_user_wallets_ux_wallet_address')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('telegram_id', sa.Text(), nullable=True),
    sa.Column('telegram_chat_id', sa.Text(), nullable=True),
    sa.Column('telegram_username', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='tbl_users_ux_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_users')
    op.drop_table('tbl_user_wallets')
    op.drop_index(op.f('ix_tbl_chat_events_user_id'), table_name='tbl_chat_events')
    op.drop_index(op.f('ix_tbl_chat_events_agent_id'), table_name='tbl_chat_events')
    op.drop_table('tbl_chat_events')
    op.drop_table('tbl_agents')
    op.drop_index(op.f('ix_tbl_agent_positions_agent_id'), table_name='tbl_agent_positions')
    op.drop_table('tbl_agent_positions')
    op.drop_index(op.f('ix_tbl_agent_actions_agent_id'), table_name='tbl_agent_actions')
    op.drop_table('tbl_agent_actions')
    # ### end Alembic commands ###
